"""Write docker-compose.yml: the world as a topology, generated from the volume manifest.

Every agent has its own container and its own recorder, and every surface an agent or a recorder
writes is a bounded image bound to that agent alone. Ten agents with ten recorders, each with a
dozen binds, is too much to keep straight by hand, and a hand-kept file is exactly where one agent
ends up mounting another's directory. So the file is generated, flat, with no anchors: what each
service was given is written out in full where a reader looks for it.

Slugs appear as the compose variables FLEET_<n>_SLUG, which scripts/roster.py writes into .env, so
the file is the same whatever roster was drawn. tests/test_compose_generated.py pins the committed
file to this generator's output; run this script after changing either, and commit both.

This is operator tooling. It runs on the host, is invoked by no component, and ships in no image.
"""

import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import volume_images  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DEST = REPO_ROOT / "docker-compose.yml"
DEFAULT_COUNT = 10
IMAGE = "space-chassis-agent"
# The vehicle's own image: the agents' image carries nothing of the vehicle (Dockerfile.agent's
# stages; John, 2026-10-10).
VEHICLE_IMAGE = "space-chassis-vehicle"
WINDOW_BIND = f"{volume_images.SOURCE_ROOT}/diode/data:/diode"
VENDOR_BINDS = (
    "./vendor/registry:/vendor/registry:ro",
    "./vendor/cargo-config.toml:/.cargo/config.toml:ro",
)

HEADER = """\
# Generated by scripts/build_compose.py from scripts/volume_images.py. Edits are lost: change the
# generator or the manifest, run `python3 scripts/build_compose.py`, and commit both.
#
# The world, as a topology. The hard rule is that no agent container has a route outward: every
# process that needs the outside lives in its own container on a network the agents cannot reach.
# Each agent's recorder holds the model credential and talks to the model; the window's far side
# is the vehicle's. The fleet reaches both through bounded volumes, never sockets of its own.
#
# Each agent is its own container on `worknet`, an internal network with no gateway, so the fleet
# can reach each other and anything they start for themselves: a control layer needs somewhere to
# run, and building one is the mission. Every surface an agent writes is a loop-mounted image
# bound to that agent alone (scripts/volume_images.py), with `create_host_path: false`, so a
# service whose image is not mounted refuses to start rather than writing to the host disk.
#
# The file declares ten agents, and every `compose up` -- a bare one too, since the monitor and the
# review panel bind every agent's record -- needs a roster of exactly ten (FLEET_COUNT=10 in .env):
# a smaller roster has no images for the agents past it, and their binds refuse. prepare_host.sh
# refuses a roster that does not match. Run it, and mount what it prints, before the first `up`.

name: space-chassis

services:
"""

LOGGING = """\
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
"""

STREAM_VARIABLES = (
    "STREAM_HOURLY_MAX",
    "STREAM_TOKEN_HOURLY_MAX",
    "STREAM_TOKEN_GLOBAL_HOURLY_MAX",
    "STREAM_REASONING_ALLOWANCE",
    "STREAM_MODEL_ALLOW_TEXT",
    "STREAM_MODEL_ALLOW_VISION",
    "STREAM_BASE_URL",
    "STREAM_API_KEY",
    "STREAM_UPSTREAM_URL",
)


def _slug(n: int) -> str:
    return f"${{FLEET_{n}_SLUG:-agent_{n}}}"


def _binds(role: str, index: int | None, count: int) -> str:
    lines = []
    for source, target, read_only in volume_images.mounts_for(role, index, count):
        lines += [
            "      - type: bind",
            f"        source: {source}",
            f"        target: {target}",
        ]
        if read_only:
            lines.append("        read_only: true")
        lines += ["        bind:", "          create_host_path: false"]
    return "\n".join(lines) + "\n"


def _environment(pairs) -> str:
    return "    environment:\n" + "".join(f"      {key}: {value}\n" for key, value in pairs)


def _agent(n: int, count: int) -> str:
    text = f"  agent_{n}:\n    image: {IMAGE}\n"
    if n == 1:
        text += "    build:\n      context: .\n      dockerfile: Dockerfile.agent\n      target: agent\n"
    if n > 1:
        text += '    profiles: ["fleet"]\n'
    text += (
        "    restart: unless-stopped\n"
        "    init: true\n"
        f"    hostname: agent_{n}\n"
        "    stop_grace_period: 20s\n"
        f"    depends_on: [recorder_{n}]\n"
        "    networks: [worknet]\n"
    )
    text += _environment(
        (
            ("AGENT_SLUG", _slug(n)),
            ("AGENT_NAME", f"${{FLEET_{n}_NAME:-agent_{n}}}"),
            ("OPENROUTER_API_KEY", '"sk-dummy"'),
            ("LLM_MODEL", f"${{HOST{n}_LLM_MODEL:-${{LLM_MODEL:-deepseek/deepseek-v4-pro}}}}"),
            (
                "CONTEXT_WINDOW_TOKENS",
                f"${{HOST{n}_CONTEXT_WINDOW_TOKENS:-${{CONTEXT_WINDOW_TOKENS:-200000}}}}",
            ),
            ("CONTEXT_WINDOW_EVICTION_TOKENS", "${CONTEXT_WINDOW_EVICTION_TOKENS:-}"),
            ("REASONING_EFFORT", "${REASONING_EFFORT:-}"),
            ("PUMP_MAX_ENTRIES", "${PUMP_MAX_ENTRIES:-32}"),
            ("PUMP_MAX_CONCURRENT", "${PUMP_MAX_CONCURRENT:-8}"),
        )
    )
    text += "    volumes:\n" + _binds("agent", n, count)
    text += "".join(f"      - {bind}\n" for bind in VENDOR_BINDS)
    text += (
        "    read_only: true\n"
        "    tmpfs:\n"
        "      - /tmp\n"
        "      - /work:size=1g,uid=1000,gid=1000\n"
        "      - /home/agent:size=256m,uid=1000,gid=1000\n"
        "      - /run/agent:size=64m,uid=1000,gid=1000\n"
        "    cap_drop: [ALL]\n"
        '    security_opt: ["no-new-privileges:true"]\n'
        "    cpus: ${AGENT_CPUS:-1.0}\n"
        "    mem_limit: ${AGENT_MEM:-3g}\n"
        "    memswap_limit: ${AGENT_MEM:-3g}\n"
        "    pids_limit: 1024\n"
    )
    return text + LOGGING


def _recorder(n: int, count: int) -> str:
    text = f"  recorder_{n}:\n    image: {IMAGE}\n"
    text += '    entrypoint: ["python", "/usr/local/lib/recorder/proxy.py"]\n'
    if n > 1:
        text += '    profiles: ["fleet"]\n'
    text += (
        "    restart: unless-stopped\n"
        f"    hostname: recorder_{n}\n"
        "    networks: [modelnet]\n"
        "    # The recorder resolves the upstream host on every request, and Docker's embedded\n"
        "    # resolver drops queries at that rate once ten sockets are busy.\n"
        "    dns: [1.1.1.1, 8.8.8.8]\n"
    )
    pairs = [
        ("AGENT_SLUG", _slug(n)),
        ("FLEET_LEDGER_PATH", "/ledger/ledger.jsonl"),
        ("TRANSCRIPT_DIR", "/transcripts"),
        ("LLM_SOCKET_PATH", "/llm/sock/core.sock"),
        ("LLM_CONSOLE_FILE", "/llm/console/console.json"),
        # Empty by default: with a base URL set, the recorder takes LLM_API_KEY, not
        # OPENROUTER_API_KEY, and an OpenRouter default here would send an empty key.
        ("LLM_BASE_URL", "${LLM_BASE_URL:-}"),
        ("LLM_API_KEY", "${LLM_API_KEY:-}"),
        ("OPENROUTER_API_KEY", "${OPENROUTER_API_KEY:-}"),
        ("RECORDER_HOURLY_MAX", "${RECORDER_HOURLY_MAX:-2400}"),
        ("RECORDER_TOKEN_HOURLY_MAX", "${RECORDER_TOKEN_HOURLY_MAX:-200000000}"),
        ("RECORDER_TOKEN_GLOBAL_HOURLY_MAX", "${RECORDER_TOKEN_GLOBAL_HOURLY_MAX:-2000000000}"),
        ("RECORDER_CORE_RESPONSE_RESERVE", "${RECORDER_CORE_RESPONSE_RESERVE:-32768}"),
        ("REQUEST_MAX_BYTES", "${REQUEST_MAX_BYTES:-16777216}"),
        ("RESPONSE_MAX_BYTES", "${RESPONSE_MAX_BYTES:-16777216}"),
        ("RECORDER_MIN_FREE_BYTES", "${RECORDER_MIN_FREE_BYTES:-134217728}"),
        ("RECORDER_CLIENT_TIMEOUT", "${RECORDER_CLIENT_TIMEOUT:-600}"),
        ("RECORDER_DEADLINE_MARGIN", "${RECORDER_DEADLINE_MARGIN:-30}"),
        ("RECORDER_UPSTREAM_DEADLINE", "${RECORDER_UPSTREAM_DEADLINE:-540}"),
        ("RECORDER_LATEST_START", "${RECORDER_LATEST_START:-480}"),
        ("RECORDER_OPERATION_TIMEOUT", "${RECORDER_OPERATION_TIMEOUT:-60}"),
        *((name, f"${{{name}:-}}") for name in STREAM_VARIABLES),
    ]
    text += _environment(pairs)
    text += "    volumes:\n" + _binds("recorder", n, count)
    text += (
        "    read_only: true\n"
        "    tmpfs: [/tmp]\n"
        "    cap_drop: [ALL]\n"
        '    security_opt: ["no-new-privileges:true"]\n'
        "    pids_limit: 512\n"
        "    mem_limit: 512m\n"
    )
    return text + LOGGING


def _fleet_monitor(count: int) -> str:
    text = (
        "  # The watcher. Reads every agent's record and writes the fleet's signals to the operator's\n"
        "  # telemetry. Read-only binds of the agents' records and the window, no network, no channel\n"
        "  # back.\n"
        "  fleet_monitor:\n"
        f"    image: {IMAGE}\n"
        '    entrypoint: ["python", "/opt/services/fleet_monitor.py"]\n'
        "    restart: unless-stopped\n"
        "    network_mode: none\n"
    )
    text += _environment(
        (
            ("MONITOR_INTERVAL_SECONDS", "${MONITOR_INTERVAL_SECONDS:-15}"),
            ("QUIET_SECONDS", "${QUIET_SECONDS:-900}"),
            ("RECORDER_HOURLY_MAX", "${RECORDER_HOURLY_MAX:-2400}"),
            ("RECORDER_TOKEN_HOURLY_MAX", "${RECORDER_TOKEN_HOURLY_MAX:-200000000}"),
        )
    )
    text += "    volumes:\n" + _binds("monitor", None, count)
    text += (
        "    read_only: true\n"
        "    tmpfs: [/tmp]\n"
        "    cap_drop: [ALL]\n"
        '    security_opt: ["no-new-privileges:true"]\n'
        "    mem_limit: 256m\n"
    )
    return text + LOGGING


def _review(count: int) -> str:
    text = (
        "  # The review panel: what an agent actually thought, from the record, read-only. It is on\n"
        "  # its own internal network because Docker will not publish a port for a container with no\n"
        "  # network at all; the agents are never on it.\n"
        "  review:\n"
        f"    image: {IMAGE}\n"
        '    entrypoint: ["python", "/opt/services/review.py"]\n'
        "    restart: unless-stopped\n"
        "    networks: [reviewnet]\n"
    )
    text += _environment(
        (
            ("REVIEW_MAX_BYTES", "${REVIEW_MAX_BYTES:-33554432}"),
            ("REVIEW_CACHE_TURNS", "${REVIEW_CACHE_TURNS:-200}"),
            ("REVIEW_DEFAULT_TURNS", "${REVIEW_DEFAULT_TURNS:-25}"),
        )
    )
    # REVIEW_PORT is the host's side of the mapping; inside, the panel listens on its default.
    text += "    ports:\n" + '      - "${REVIEW_BIND:-127.0.0.1}:${REVIEW_PORT:-8090}:8090"\n'
    text += "    volumes:\n" + _binds("review", None, count)
    text += (
        "    read_only: true\n"
        "    tmpfs: [/tmp]\n"
        "    cap_drop: [ALL]\n"
        '    security_opt: ["no-new-privileges:true"]\n'
        "    mem_limit: 512m\n"
        "    pids_limit: 256\n"
    )
    return text + LOGGING


def _diode() -> str:
    text = (
        "  # The window's fixture: contract/fake_diode.py, which satisfies the contract and models\n"
        "  # nothing; `vehicle` below is the real implementation, and one or the other runs. It binds\n"
        "  # the whole shared window image; each agent binds only its own directory in it.\n"
        "  diode:\n"
        f"    image: {IMAGE}\n"
        '    entrypoint: ["python", "/opt/fake/fake_diode.py"]\n'
        "    restart: unless-stopped\n"
        '    profiles: ["diode"]\n'
        "    # Its interface is the volume, so it needs no network at all (spec section 5).\n"
        "    network_mode: none\n"
    )
    text += _environment(
        (
            ("DIODE_DIR", "/diode"),
            ("DIODE_POLL_SECONDS", "${DIODE_POLL_SECONDS:-5}"),
            ("DIODE_HOURLY_MAX", "${DIODE_HOURLY_MAX:-120}"),
        )
    )
    text += f"    volumes:\n      - {WINDOW_BIND}\n"
    text += "      - ./contract/fake_diode.py:/opt/fake/fake_diode.py:ro\n"
    text += (
        "    read_only: true\n"
        "    tmpfs: [/tmp]\n"
        "    cap_drop: [ALL]\n"
        '    security_opt: ["no-new-privileges:true"]\n'
        "    mem_limit: 512m\n"
    )
    return text + LOGGING


def _vehicle(count: int) -> str:
    text = (
        "  # The vehicle: the reference console, serving into the same window image the fleet reads.\n"
        "  # `diode` above is the contract fixture; start one or the other. No network at all: its\n"
        "  # interface is the window volume, as the fixture's is (spec 5), and its code opens no\n"
        "  # socket. On `worknet` it was a named host the agents could address and whose restarts\n"
        "  # they could observe, which is evidence about hidden vehicle state outside the instruments.\n"
        "  # Its image is its own, the only one carrying /opt/vehicle; built only by name, with\n"
        "  # `docker compose --profile vehicle build`, and its entrypoint is the serve script.\n"
        "  vehicle:\n"
        f"    image: {VEHICLE_IMAGE}\n"
        "    build:\n      context: .\n      dockerfile: Dockerfile.agent\n      target: vehicle\n"
        "    restart: unless-stopped\n"
        # docker-init forwards SIGTERM to the exec'd console, which installs no handler: as PID 1 it
        # would ignore `docker stop` until the SIGKILL.
        "    init: true\n"
        '    profiles: ["vehicle"]\n'
        "    network_mode: none\n"
    )
    text += _environment(
        (
            ("DIODE_DIR", "/diode"),
            ("VEHICLE_DIR", "/opt/vehicle"),
            ("VEHICLE_STATE_DIR", "/state"),
            # Which windows to serve: every agent's slug, from the roster in .env.
            ("VEHICLE_SLUGS", "${VEHICLE_SLUGS:-${FLEET_SLUGS:-vehicle}}"),
            ("VEHICLE_SCENARIO", "${VEHICLE_SCENARIO:-nominal}"),
            ("VEHICLE_SEED", "${VEHICLE_SEED:-0}"),
            ("DIODE_POLL_SECONDS", "${DIODE_POLL_SECONDS:-5}"),
            ("VEHICLE_RING_SLOTS", "${VEHICLE_RING_SLOTS:-300}"),
        )
    )
    text += f"    volumes:\n      - {WINDOW_BIND}\n" + _binds("vehicle", None, count)
    text += (
        "    read_only: true\n"
        "    tmpfs: [/tmp]\n"
        "    cap_drop: [ALL]\n"
        '    security_opt: ["no-new-privileges:true"]\n'
        "    mem_limit: 512m\n"
    )
    return text + LOGGING


NETWORKS = """\
networks:
  # No gateway. Members can reach each other and nothing else.
  worknet:
    internal: true
  # The recorders' network. The agents are not on this one.
  modelnet: {}
  # The review panel's own network: no gateway, and no other member.
  reviewnet:
    internal: true
"""


def build_text(count: int = DEFAULT_COUNT) -> str:
    """The whole compose file for a fleet of count agents."""
    parts = [HEADER]
    for n in range(1, count + 1):
        parts.append(_agent(n, count))
        parts.append("\n")
        parts.append(_recorder(n, count))
        parts.append("\n")
    parts += [
        _fleet_monitor(count),
        "\n",
        _review(count),
        "\n",
        _diode(),
        "\n",
        _vehicle(count),
        "\n",
        NETWORKS,
    ]
    return "".join(parts)


def main() -> int:
    text = build_text(DEFAULT_COUNT)
    descriptor, temporary = tempfile.mkstemp(dir=DEST.parent, prefix=".docker-compose.", text=True)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(text)
    os.chmod(temporary, 0o644)
    os.replace(temporary, DEST)
    print(f"wrote {DEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
